core/urls.py
from django.conf.urls import url, include	

from core import views


app_name = 'core'


urlpatterns = [
	url(r'^registration/$', views.registration_user_view, name='registration_user_view'),
	url(r'^login/$', views.login_user_view, name='login_user_view'),
	url(r'^logout/$', views.logout_user, name='logout_user'),
	url(r'^profile/$', views.profile_view, name='profile_view'),

]

online_store/urls.py
from django.conf import settings
from django.conf.urls import url, include	
from django.conf.urls.static import static
from django.contrib import admin
from django.views.static import serve

from . import views


app_name = 'online_store'


urlpatterns = [
    url(r'^$', views.main_page_view, name='main_page_view'),
    url(r'^admin/', admin.site.urls),
    url(r'^category/', include('categories.urls', namespace='categories')),
    url(r'^', include('core.urls')),
    url(r'^', include('shopping_carts.urls')),
    url(r'^', include('comments.urls')),
]

urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping_carts/urls.py
from django.conf.urls import url, include	
from . import views

app_name = 'shopping_carts'

urlpatterns = [
	url(r'^shopping-cart/$', views.shopping_cart_view, name='shopping_cart_view' ),
	url(r'^add-shopping-cart-item/(?P<product_id>[\w]+)$', views.add_shopping_cart_item, name='add_shopping_cart_item' ),
	url(r'^payment-for-shopping-cart-items/$', views.payment_for_shopping_cart_items, name='payment_for_shopping_cart_items' ),
	url(r'^successful-payment/$', views.successful_payment_view, name='successful_payment_view'),
	url(r'^delete-shopping-cart-item/(?P<shopping_cart_item_id>[\w]+)$', views.delete_shopping_cart_item, name='delete_shopping_cart_item' ),
]

shopping_carts/models.py
from django.db import models




class ShoppingCartItem(models.Model):
	shopping_cart = models.ForeignKey('ShoppingCart', related_name='shopping_cart_items')
	product = models.ForeignKey('products.Product', related_name='shopping_cart_items')
	quantity = models.PositiveIntegerField(default=1)
	
	def __str__(self):
		return '{}, {} х {}'.format(self.shopping_cart.__str__, self.product.name, self.quantity)

	def price(self):
		return self.product.price * self.quantity



class ShoppingCart(models.Model):

	def __str__(self):
		rep_str = ''
		rep_str += '{} shopping cart'.format(self.id)
		return rep_str
		

	def total_price(self):
		tot_price = 0
		for i in self.shopping_cart_items.all():
			tot_price += i.price()
		return tot_price

shopping_carts/forms.py
from django import forms


class ProductIdForm(forms.Form):
	product_id = forms.CharField(max_length=5)

class ShoppingCartItemIdForm(forms.Form):
	shopping_cart_item_id = forms.CharField(max_length=5)

shopping_carts/views.py
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.db.utils import IntegrityError
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse

from products.models import Product

from .models import ShoppingCart, ShoppingCartItem
from .forms import ProductIdForm, ShoppingCartItemIdForm


def shopping_cart_view(request):
	template = 'shopping_carts/shopping_cart.html'
	context = {}
	
	shopping_cart_items = ShoppingCartItem.objects.filter(
		shopping_cart__id=request.session['shopping_cart_id'])
	if shopping_cart_items:
		context['shopping_cart_items'] = shopping_cart_items
	else:
		messages.info(request, 'Your shopping cart is empty')

	return render (request, template, context)


def add_shopping_cart_item(request, product_id):
	product = Product.objects.get(id=product_id)
	shopping_cart = ShoppingCart.objects.get(id=request.session['shopping_cart_id'])
	
	try:
		ShoppingCartItem.objects.filter(shopping_cart__id=request.session['shopping_cart_id']
			).get(product__id=product_id)

	except ObjectDoesNotExist:
		ShoppingCartItem.objects.create(
					shopping_cart=shopping_cart, 
					product=product,
		)	
	else:
		messages.warning(request, 'You already own this product in your shopping cart')
	
	return HttpResponseRedirect(request.META['HTTP_REFERER'])


def payment_for_shopping_cart_items(request):
	if request.user.is_authenticated:
		shopping_cart_items = ShoppingCartItem.objects.filter(
			shopping_cart__id=request.session['shopping_cart_id'])
		for item in shopping_cart_items:
			try:
				product = item.product
				product.stock -= item.quantity
				product.save()
			except IntegrityError:
				messages.warning(request, 'Not enough items in stock')
				return HttpResponseRedirect(reverse('shopping_carts:shopping_cart_view'))
			else:
				shopping_cart_items.delete()
				return HttpResponseRedirect(reverse('shopping_carts:successful_payment_view'))
	else:
		return HttpResponseRedirect(reverse('core:login_user_view'))


def successful_payment_view(request):
	template = 'shopping_carts/successful_payment.html'
	contex = {}

	messages.success(request, 'Payment made successfully')
	return render(request, template, contex)


def delete_shopping_cart_item(request, shopping_cart_item_id):
	ShoppingCartItem.objects.get(id=shopping_cart_item_id).delete()
	return HttpResponseRedirect(request.META['HTTP_REFERER'])

shopping_carts/templates/shopping_carts/base.html
{% extends "online_store/base.html" %}

{% block base_content %}
	{% block content %}
	{% endblock content %}
{% endblock base_content %}

shopping_carts/templates/shopping_carts/shopping_cart.html
{% extends 'shopping_carts/base.html' %}


{% block content %}
	<section class="shopping-cart-items">
		{% for item in shopping_cart_items %}
		<article class="shopping-cart-item">
			<!-- 1 -->
			<div class="shopping-cart-item-image">
				<img src="{{ item.product.image.url }}">
			</div>
			<!-- 2 -->
			<div class="shopping-cart-item-full-name">
				<a href="{% url 'categories:products:product_details' item.product.category item.product.name %}"><span class="full-name">{{ item.product.full_name }}</span></a>
			</div>
			<!-- 3 -->
			<div class="shopping-cart-item-count">
				
			</div>
			<!-- 4 -->
			<div class="shopping-cart-item-price">
				<span class="price">{{ item.product.price }} $</span>
			</div>
			<!-- 5 -->
			<div class="shopping-cart-item-del-item">
				<form action="{% url 'shopping_carts:delete_shopping_cart_item' item.id %}" method="post">
				{% csrf_token %}
					<input type="hidden" value="{{ item.id }}" name="shopping_cart_item_id" >
					<input type="submit" value="Remove from cart" name="del_from_cart" >
				</form>
			</div>
		</article>
		{% endfor %}
	</section>

	{% if shopping_cart_items %}
	<section class='shopping-cart-payment-form'>
		<article >
			<div></div>
			<div class="shopping_cart-total-price">
				<span>{{shopping_cart_items.0.shopping_cart.total_price}} $</span>
			</div>
			<div class='shopping-cart-payment-form'>
				<form action="/payment-for-shopping-cart-items/" method="post">
				{% csrf_token %}
					<input type="submit" value="Payment" name="payment_for_shopping_cart_items" >
				</form>
			</div>
		</article>
	</section>
	{% endif %}
{% endblock content %}

shopping_carts/templates/shopping_carts/successful_payment.html
{% extends 'shopping_carts/base.html' %}


{% block content %}

	{% for message in messages %}
		{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
			<p>{{ message }}</p>
		{% endif %}
	{% endfor %}

{% endblock content %}