categories/urls.py
from django.conf.urls import url, include

from . import views


app_name = 'categories'


urlpatterns = [
	url(r'^all/$', views.all_categories, name='all_categories'),
	url(r'^', include('products.urls', namespace='products')),
]

core/urls.py
from django.conf.urls import url, include	

from core import views


app_name = 'core'


urlpatterns = [
	url(r'^registration/$', views.registration_user_view, name='registration_user_view'),
	url(r'^login/$', views.login_user_view, name='login_user_view'),
	url(r'^logout/$', views.logout_user, name='logout_user'),
	url(r'^profile/$', views.profile_view, name='profile_view'),

]

online_store/urls.py
from django.conf import settings
from django.conf.urls import url, include	
from django.conf.urls.static import static
from django.contrib import admin
from django.views.static import serve

from . import views


app_name = 'online_store'


urlpatterns = [
    url(r'^$', views.main_page_view, name='main_page_view'),
    url(r'^admin/', admin.site.urls),
    url(r'^category/', include('categories.urls', namespace='categories')),
    url(r'^', include('core.urls')),
    url(r'^', include('shopping_carts.urls')),
    url(r'^', include('comments.urls')),
]

urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping_carts/urls.py
from django.conf.urls import url, include	
from . import views

app_name = 'shopping_carts'

urlpatterns = [
	url(r'^shopping-cart/$', views.shopping_cart_view, name='shopping_cart_view' ),
	url(r'^add-shopping-cart-item/(?P<product_id>[\w]+)$', views.add_shopping_cart_item, name='add_shopping_cart_item' ),
	url(r'^payment-for-shopping-cart-items/$', views.payment_for_shopping_cart_items, name='payment_for_shopping_cart_items' ),
	url(r'^successful-payment/$', views.successful_payment_view, name='successful_payment_view'),
	url(r'^delete-shopping-cart-item/(?P<shopping_cart_item_id>[\w]+)$', views.delete_shopping_cart_item, name='delete_shopping_cart_item' ),
]

online_store/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username', 'password', 'email', 'first_name', 'last_name']


class LoginForm(forms.Form):
	username = forms.CharField(max_length=100)
	password = forms.CharField(widget=forms.PasswordInput())

online_store/views.py
from django.shortcuts import render

from shopping_carts.models import ShoppingCart
from products.models import Product

from .functions import get_list_with_random_ids


def main_page_view(request):
	template = 'online_store/base.html'
	context = {}
	
	if request.user.is_authenticated():
		request.session['shopping_cart_id'] = request.user.shopping_cart.id
	else:
		shopping_cart = ShoppingCart.objects.create()
		request.session['shopping_cart_id'] = shopping_cart.id

	products = Product.objects.filter(id__in=get_list_with_random_ids(model=Product, count=5))
	context['products'] = products
	return render(request, template, context)

online_store/templates/online_store/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="{% static 'online_store/css/base.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'online_store/css/navbase.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'categories/css/category_list.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'products/css/one_category_products.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'shopping_carts/css/shopping_cart.css' %}">
	<title>The simplest online store!</title>
</head>

<body>
	<header>
		<nav class="base">
			<a href="/">Main</a>
			<a href="#">About company</a>
			<a href="{% url 'categories:all_categories' %}">Categories</a>
			<a href="#">Delivery</a>
			<a href="{% url 'core:registration_user_view' %}">Registration</a>
			{% if not user.is_authenticated %}
				<a href="{% url 'core:login_user_view' %}">Login</a>
			{% else %}
				<a href="{% url 'core:logout_user' %}">Logout({{ user.username }})</a>
			{% endif %}
			<a href="{% url 'shopping_carts:shopping_cart_view' %}">Cart</a>
			{% if user.is_authenticated %}
				<a href="{% url 'core:profile_view' %}">Profile</a>
			{% endif %}				
		</nav>
	</header>
	<section class="content">
		{% if messages %}
		<article class='info-message'>
			{% for message in messages %}
				{% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
					<li>{{ message }}</li>
				{% endif %}
				{% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
					<li>{{ message }}</li>		
				{% endif %}
			{% endfor %}
		</article>
		{% endif%}
		{% block base_content %}
			<ul class="main-item-row">
			{% for product in products %}
				<a class="main-item" href="{% url 'categories:products:product_details' product.category.name product.name %}">
					<!-- <li class="main-item"> -->
						<div class="wrapper-img"><img src="{{ product.image.url }}" alt="{{product.name}}"></div>
						<div class="wrapper-name">{{ product.full_name }}</div>
					<!-- </li> -->
				</a>
			{% endfor %}
			</ul>
		{% endblock base_content %}
	</section>
	<footer>
		<nav>
			<ul>
				<li><p>+375 29 123 45 67</p></li>
				<li><p>+375 33 123 45 67</p></li>
				<li><p>+375 25 123 45 67</p></li>
				<li><p>+375 29 123 45 67</p></li>
			</ul>
			<ul>
				<li><a href="#">About company</a></li>
				<li><a href="#">Delivery</a></li>
			</ul>
			<ul>
				<li><a href="#">Manufacturers</a></li>
				<li><a href="#">Service centers</a></li>
			</ul>
		</nav>
	</footer>
</body>
</html>