core/urls.py
from django.conf.urls import url, include	

from core import views


app_name = 'core'


urlpatterns = [
	url(r'^registration/$', views.registration_user_view, name='registration_user_view'),
	url(r'^login/$', views.login_user_view, name='login_user_view'),
	url(r'^logout/$', views.logout_user, name='logout_user'),
	url(r'^profile/$', views.profile_view, name='profile_view'),

]

online_store/urls.py
from django.conf import settings
from django.conf.urls import url, include	
from django.conf.urls.static import static
from django.contrib import admin
from django.views.static import serve

from . import views


app_name = 'online_store'


urlpatterns = [
    url(r'^$', views.main_page_view, name='main_page_view'),
    url(r'^admin/', admin.site.urls),
    url(r'^category/', include('categories.urls', namespace='categories')),
    url(r'^', include('core.urls')),
    url(r'^', include('shopping_carts.urls')),
    url(r'^', include('comments.urls')),
]

urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

from django.conf import settings
from django.conf.urls.static import static

from . import views


app_name = 'products'


urlpatterns = [
	url(r'^(?P<category_name>[\w\s]+)/$', views.one_category_products, name='one_category_products'),
	url(r'^(?P<category_name>[\w\s]+)/(?P<product_name>[\w\s\,\-\\/]+)$', views.product_details, name='product_details'),
]

shopping_carts/urls.py
from django.conf.urls import url, include	
from . import views

app_name = 'shopping_carts'

urlpatterns = [
	url(r'^shopping-cart/$', views.shopping_cart_view, name='shopping_cart_view' ),
	url(r'^add-shopping-cart-item/(?P<product_id>[\w]+)$', views.add_shopping_cart_item, name='add_shopping_cart_item' ),
	url(r'^payment-for-shopping-cart-items/$', views.payment_for_shopping_cart_items, name='payment_for_shopping_cart_items' ),
	url(r'^successful-payment/$', views.successful_payment_view, name='successful_payment_view'),
	url(r'^delete-shopping-cart-item/(?P<shopping_cart_item_id>[\w]+)$', views.delete_shopping_cart_item, name='delete_shopping_cart_item' ),
]

products/models.py
from django.db import models

from manufacturers.models import Manufacturer
from categories.models import Category
from shopping_carts.models import ShoppingCart



class Product(models.Model):
	slug = models.SlugField(max_length=10, unique=True, 
		verbose_name='Product code')
	category = models.ForeignKey(Category, related_name='products')
	manufacturer = models.ForeignKey(Manufacturer)
	name = models.CharField(max_length=100, unique=True)
	price = models.DecimalField(max_digits=12, decimal_places=2)
	description = models.TextField(blank=True)
	image = models.ImageField(upload_to='products/images/', blank=True)
	stock = models.PositiveIntegerField()
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	


	def __str__(self):
		return '{} {} {}, {}$'.format(self.category, self.manufacturer, self.name, self.price)

	def url_name(self):
		return self.name.replace(' ', '-')

	def full_name(self):
		return self.category.name + ' ' +self.manufacturer.name + ' ' + self.name
	

products/views.py
from django.shortcuts import render
from django.views import generic

from shopping_carts.views import add_shopping_cart_item
from comments.forms import CommentForm
from comments.models import Comment

from .models import Product


class AllProducts(generic.ListView):
	template_name = 'products/all_products.html'
	context_object_name = 'products'

	def get_queryset(self):
		return Product.objects.all()


def one_category_products(request, category_name):
	template = 'products/one_category_products.html'
	products = Product.objects.filter(category__name__iexact=category_name)
	context = {'products': products}
	return render(request, template, context)


# Should I take category_name parameter?
# I have doubts about 'get' method.
def product_details(request, category_name, product_name):
	template = 'products/product_details.html'
	product = Product.objects.get(name__iexact=product_name.replace('-', ' '))
	comment_form = CommentForm()
	comments = Comment.objects.filter(product__id=product.id).order_by('-created')
	context = {'product': product, 'comment_form': comment_form, 'comments': comments}

	if request.method == 'POST':
		comment_form = CommentForm(request.POST)
		
		if comment_form.is_valid():
			user = request.user
			Comment.objects.create(user=user, product=product, text=comment_form.cleaned_data['text'])

		if request.POST.get('add_to_cart'):
			add_shopping_cart_item(request, product.id)

	return render(request, template, context)

products/templates/products/all_products.html
{% extends "products/base.html" %}

{% block content %}
	{% for product in products %}
		{{ product }}
	{% endfor %}
{% endblock content%}

products/templates/products/base.html
{% extends "online_store/base.html" %}

{% block base_content %}
	{% block content %}{% endblock content %}
{% endblock base_content %}

products/templates/products/one_category_products.html
{% extends "products/base.html" %}


{% block content %}

<h5 class="category-name">{{products.0.category.name}}{{products|pluralize}}</h5>
<ul class="one-category-products">
	{% for product in products %}
	<li>
		<div><img src="{{ product.image.url }}"></div>
		<div>
			<a href="{% url 'categories:products:product_details' product.category.name|lower product.url_name|lower %}">{{ product.manufacturer.name }} {{ product.name }}</a>
			<ul>
				<li>Code: {{ product.slug }}</li>
				<li>Manufacturer: {{ product.manufacturer.name }}</li>
				<li>Stock: {{ product.stock }}</li>

			</ul>
		</div>
		<div>
			<p>{{ product.price }} $</p>
			<form action="{% url 'shopping_carts:add_shopping_cart_item' product.id %}" method="post">
				{% csrf_token %}
				<input type="submit" class="btn" value="Add to cart" name="add_to_cart">
			</form>
		</div>
	</li>
	{% endfor %}
</ul>

{% endblock content %}

products/templates/products/product_details.html
{% extends "products/base.html" %}
{% load staticfiles %}
{% load static %}


{% block content %}
<section class="image-price-buttom-description">
	<div class="wrapper-image">
		<img src="{{ product.image.url }}" alt="{{product.fulll_name}}"><br>
	</div>
	<div class="wrapper-price-button-discription">
		{% if product.description %}
		<p>{{ product.description }}</p>
		{% endif %}
		<div class="wrapper-span-form">
		<span>{{ product.price }} $</span>
			<form action="" method="post">
			{% csrf_token %}
				<input type="submit" value="Add to cart" name="add_to_cart" class="add-to-cart">
			</form>
		</div>
	</div>
</section>
<section class="product-details"> 
	<h6>Details</h6>
	<ul >
		<li>Code: {{ product.slug }}</li>
		<li>Category: {{ product.category }}</li>
		<li>Manufacturer: {{ product.manufacturer.name }}</li>
		<li>Model: {{ product.name }}</li>
		<li>Stock: {{ product.stock }}</li>
	</ul>
</section>
{% if user.is_authenticated %}
<article class="comment-form">
	<form action="" method='post'>
	{% csrf_token %}
	{{ comment_form.text }}
	<input type="submit" value="Add comment">
</article>
{% endif %}
<article class="comments">
	{% if comments %}
		{% for comment in comments %}
		<ul>
			<li class="comment-username"><time datetime="{{ comment.created|date:'c' }}" title="{{ comment.created|date:'d.m.y' }} in {{ comment.created|date:'H:i' }}" pubdate>{{ comment.created }}</time> <span>{{ comment.user.username }}</span></li>
			<li class="comment-text">{{ comment.text }}</li>
			<li class="comment-image"><span>{{ comment.likes.count }}	</span><a href="/add_remove_like/{{ comment.id }}/"><img src="{% static 'comments/like.png' %}"></a></li>
		</ul>
		{% endfor %}
	{% else %}
		<p>No comments yet</p>
	{% endif %}
</article>

<div itemscope itemtype="http://schema.org/Book">
I love that Introducing HTML5 by Bruce Lawson and Remy Sharp
¬ (ISBN 0321784421)
</div>
{% endblock content %}